sudo: required

notifications:
  slack:
    rooms:
      - utcoupe-utc:cW8wDAodXN9NB6fgPt356vFQ#github
    on_success: always # default: always
    on_failure: always # default: always

services:
  - docker

install:
  - docker pull utcoupe/coupe20:utcoupe-ros-kinetic-amd64

script:
  - source scripts/run_travis_build.sh
