# Action used to move any actuator connected to the robot. Enter the actuator name (defined
# in the node's XML) with movement params.

string name   # Actuator id.
int32 id      # Can be directly used instead of the string name. Ignored if name is defined.

int32 timeout # In ms. Replaced by a default timeout if negative or null. 

string order  # Movement type passed in to the arduinos/AX12s (TODO TO BE DEPRECATED ?). JOINT or WHEEL

string preset # Can be used to find a defined position in the XML. Ignored if param is defined.
string param  # Manual destination value (position, speed...) if no preset exists for your value.

---
bool success 
---
